default_chain: stride-testnet
chains:
  stride-testnet:
    key: yasa
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:16657
    grpc-addr: http://127.0.0.1:16090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia-testnet:
    key: yasa
    chain-id: GAIA
    rpc-addr: http://38.242.236.111:23657
    grpc-addr: http://38.242.236.111:23090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
